language: c
sudo: false
env:
  global:
    - secure: "iWrZJIjEBSSwKPqwd6pxajhTmHss9CfB94sCCr4KxTreNrHd9X0exP5dSjiZzfmvUaMlFTLACFIWOHxcedjLNYgK4ZWQTj4qX/m9TUpOO2isN5K6ZbNJxzrTcJavU86MwxmT/XPFZKTPHrNQ0+711tT5zZ7cWEiV/QwRbrdYC438UjHQ781YIap2ko0bmp6tOMTrZjnm0dIB6ngMO2wYhxSel3LZ4vEhOgxZHKL3dXyynwIVmVtLMIJ9CHQ4Tj8lnbGnNc3VNCeoQB2YUe0kV0L6Jxlt9z3E3vKnYjT133oZnN+86I10C9+1MXuYni9XPvJ2FhEmUMiumSda2L5u+wE7r/esoGwUq59R7iEh/TPZmfREjHBRAvinS3OtfLifJs3WYkoa9qSfkk0V3d8hmqatlk+ngFPL3aN6UuAX5+dA0K5TxQ8RzIf16IoljZ7ruS3GocM5/7QYBvwrl8tRk7S0djEmuS5M4y8AHVnKzUVozDJFixQAjtW4Qx8XrLrv6h72dUyhcOw98IGWXbUKwhW3crSlkONgmi+lcf1fIzAJLvHksTpX7BHnN4+G7trgNo47qI0wBlhenEFLQYV4WwxOO01/eYClnm2XAV+s9CSyABYfxgf7LyagBq6jXWyqTLnF7Onte0jJkbv2LCRKOXR5xxJmEZTyBD/RwGWY3io="
matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      sudo: required
    - os: linux
      sudo: required
      dist: trusty
  #allow_failures:
  #  - os: linux
  #    sudo: false
before_install:
  - ./install-icc.sh
  - source ~/.bashrc
script:
  # C99 compiler
  - icc    -std=c99          test/test.c           -o test/testc
  # C++11 compiler
  - icpc   -std=c++11        test/test.cxx         -o test/testcxx
  # Cilk extensions in C (on by default)
  - icc    -std=c99          test/testcilk.c       -o test/testcilkc
  # MPI-3 library
  - mpiicc -std=c99          test/testmpi.c        -o test/testmpic
  # IPP library in C
  - icc    -std=c99    -ipp  test/testipp.c        -o test/testippc
  # DAAL library in C++
  - icpc   -std=c++11  -daal test/testdaal.cxx     -o test/testdaalcxx
  # TBB library for C++
  - icpc   -std=c++11  -tbb  test/testtbb.cxx      -o test/testtbbcxx
  # MKL CBLAS library
  - icc    -std=c99    -mkl  test/testmkl.c        -o test/testmklc
  # Fortran MKL runtime
  - ifort  -std08      -mkl  test/testmkl.f90      -o test/testmklf90
  # Fortran 90+ compiler
  - ifort  -std08 -fpp       test/test.f90         -o test/testf90
  # Fortran MPI-2 library
  - mpiifort  -std08 -fpp    test/testmpi.f90      -o test/testmpif90
  # Fortran 2008 MPI-3 library
  - mpiifort  -std08 -fpp    test/testmpi_f08.f90  -o test/testmpif08
notifications:
  email:
    on_success: change
    on_failure: change
