language: c
sudo: false
env:
  global:
    # Intel Composer
    #- secure: "UBudgeEwCcW9lHwFM8MBudW8IisCE7nsgdNeeKY8Fe+ProrcR4xk/e/E0BeRrLrggCz6NYRt8DYupsr1+cmCg3+sKeMaheinRjLV/QX0J4JvITAlPvDVS8OmEMHaehchgIajSDpAuh02TK4GSuDuLVTIZj52MC4xXVZdZQGkiTFfUbvOumlUN4LrWQgSLpoGaUDg97KNIkI8sMIb9yy0DkD3cz7/isC0p2Dh5Ks9jsnM7Tu5ZVqk8zkR3aHMoftE9eQPAtOszMCFm/xG4YUp0qHcOC2xA4FNFabInFGKCGI0JS2R/L3+4mSeg8x0SIBLC75Ru+O9PLgzyaGfRn8q2ohyDnWtznF4LrWhxl8WnG42tooRKNW389OT+n4jYs4bj/Zm6vkTTDbGd5hrBEqBU8gr6SqIWnROXkVWM1CL7gNT19IkVJ1wgKkJqIaYfvXbXTokIjpheEbv113yJSvFnnXfoUoQ2eOrmTX2Otqm4/t6z8GObUClpmSZKBmPSwn1CEg1Ej2pzrX33TIrP1sh9l+h9p8PF0Mq8sL0I5wFeTKHn9E4xsoh4UdsOSkzhFsB+ritmJPZWnGNuLnLV6qf1E5q9LDs3AaaUUBVr6NayWrmUOrFR/v58VFT5907o4nQbiZfB0L+z3h9Al2wMxRtzX8cf7VSJp+GvQsqDRMq8zY="
    # Intel Parallel Studio
    - secure: "pRthq4b59pqfe333JklO6VAuRR2OTfecg0X2cAznmzsmNj8AF/hL1HQCoUScPwSwLBfVCfaEK/sT1jXCG3nz1/TQtwtVuarQuylSzxnqJZJEubDOhpT8nNnvAqVvgGzsq7z4FgBUmk+Nv6nrFkf8FGqfgRY3/djeogmNWs8FYRPXeqnBUTix5mlTY1rim940RdTzipo8IlXhpux9Dwjr6U+jKaKDEqq3t5AMqmBAcF5KulNJhCbSQhIu3hNs7hhMGPyxbbX9FfYtBQ45IU87FqSOfUfp2jOmw+h1N6XMIlqXTtshR3IditvXkhtOY9Aw6QE39oX1ivCFzqnk2iFmNArWnOHIltTT72zKuwURX2WQU6y7FfsF1NrtGijHJsfqieRDgBWnfoNFm9nCJQSv6g/tFXsT95dmvipzvzqSGpkArTc6kWBkFnfKy9FfbLnHm9V2L+PFI5HFXNZaEobmM4FKHSGxkQNwBoXufnmCWV2ZIf3uLfwERqL92Sas2lkoOV/mEznI30AeowTnCG1+cUvFRZOrv+5UFUuRSQi83DBFzsXQJjoYEnezA9kVWSVAuamBKRiOZ5YvLngiRJPmIdUC3m4N/6zOK68ouCJy06S/LzrFkWNMS74zwYI1ICiJt7Yt4Khzl35KoP+C1NOLuylj1OyIipActGoOH8z71a4="
matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      sudo: required
    - os: linux
      sudo: required
      dist: trusty
before_install:
  - ./install-icc.sh
  - source ~/.bashrc
script:
  - icc -o test/test test/test.c
notifications:
  email:
    on_success: change
    on_failure: change
